theme:
  name: material
  highlightjs: True
  hljs_style: shades-of-purple
  locale: es
  language: gl
  include_homepage_in_sidebar: True
  prev_next_buttons_location: both
  favicon: "images/favicon.png"
  logo: "images/logo.png"
  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - fontawesome_markdown

site_name: JFSanchez
site_url: https://jfsanchez.es/docs
repo_url: https://github.com/jfsanchez/
site_author: Jose Sánchez
copyright: 2023 - Jose Sánchez
