theme:
  name: material
  highlightjs: True
  hljs_style: shades-of-purple
  locale: es
  language: gl
  include_homepage_in_sidebar: True
  prev_next_buttons_location: both
  favicon: "images/favicon.png"
  logo: "images/logo.png"
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

site_name: JFSanchez
site_url: https://jfsanchez.es/docs
repo_url: https://github.com/jfsanchez/
site_author: Jose Sánchez
copyright: 2023 - Jose Sánchez
